apiVersion: apps/v1 
kind: Deployment
metadata:
  name: mysql-volume 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql   
    spec:
      containers:
      - name: mysql-volume
        image: mysql:8
        volumeMounts:
        - name: data-volume
          mountPath: /var/lib/mysql
        env:
          - name: MYSQL_DATABASE
            value: eazytraining
          - name: MYSQL_USER
            value: eazy 
          - name: MYSQL_PASSWORD 
            value: eazy 
          - name: MYSQL_ROOT_PASSWORD 
            value: password 
        ports:
        - containerPort: 33060 
      volumes:
        - name: data-volume 
          hostPath:
            path: /data-volume 