apiVersion: v1
kind: Pod
metadata:
  name: webapp-color-blue
  labels:
    app: web 
  namespace: production
spec:
  containers:
  - name: webapp-color
    image: mmumshad/simple-webapp-color
    env:
      - name: APP_COLOR
        value: blue 
    ports:
      - containerPort: 8080