--- 
apiVersion: v1
kind: Service
metadata:
  name:  database-svc
  labels:
    app: wordpress
spec:
  type: ClusterIP
  selector:
    app:  wordpress
  ports:
  - protocol:  TCP
    port:  33060
    targetPort: db-port
...