---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - name: wordpress
        image: wordpress:6.1-apache  
        env:
        - name: WORDPRESS_DB_HOST
          value: database-svc
        - name: WORDPRESS_DB_NAME
          value: eazytraining
        - name: WORDPRESS_DB_USER
          value: eazy 
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: secret-database 
              key: mysql_password
        ports:
        - name: wp-port
          containerPort: 80  
        volumeMounts:
        - name: wp-data
          mountPath: /var/www/html

      volumes:
        - name: wp-data
          hostPath:
            path: /data 
---